// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkurt0BfZX4ACFSuYkJO_tipZbv5PdWbw',
    appId: '1:72939033085:ios:4b33a42d14764ed92f0994',
    messagingSenderId: '72939033085',
    projectId: 'final-project-8f5cf',
    storageBucket: 'final-project-8f5cf.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkurt0BfZX4ACFSuYkJO_tipZbv5PdWbw',
    appId: '1:72939033085:ios:4b33a42d14764ed92f0994',
    messagingSenderId: '72939033085',
    projectId: 'final-project-8f5cf',
    storageBucket: 'final-project-8f5cf.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPo7Ya_s1cNJAHvUaHN8DYr0gElYJxh9I',
    appId: '1:72939033085:web:1f8d034722a239322f0994',
    messagingSenderId: '72939033085',
    projectId: 'final-project-8f5cf',
    authDomain: 'final-project-8f5cf.firebaseapp.com',
    storageBucket: 'final-project-8f5cf.firebasestorage.app',
    measurementId: 'G-2TTG542F4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDamZkjhXFGRQmD-6akrwcxG-GbITcbsMQ',
    appId: '1:72939033085:android:1a3f754f5adadf2f2f0994',
    messagingSenderId: '72939033085',
    projectId: 'final-project-8f5cf',
    storageBucket: 'final-project-8f5cf.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPo7Ya_s1cNJAHvUaHN8DYr0gElYJxh9I',
    appId: '1:72939033085:web:901f72c5dd0996bb2f0994',
    messagingSenderId: '72939033085',
    projectId: 'final-project-8f5cf',
    authDomain: 'final-project-8f5cf.firebaseapp.com',
    storageBucket: 'final-project-8f5cf.firebasestorage.app',
    measurementId: 'G-53D10EPC48',
  );
}
